---
title: "Pruebas no parametricas con una y dos muestras numericas"
author: "Jaime Riquelme"
date: "2024-11-10"
output: pdf_document
---

# Pruebas no parametricas con una y dos muestras numericas

En este documentos se verán pruebas alternativas no parametricas para las pruebas t de student (para una y dos medias) y ANOVA (para más de dos medias).

## Prueba suma de rangos de Wilcoxon

Como vimos en la prueba t, si es que un escenario no cumple alguna de sus condiciones, no hay garantias de que el resultado sea valido, y en consecuena las conclusiones que se obtengan podrian ser equivocadas.

Es por eso que existe esta alternativa para el caso que no se cumplan las condiciones de la prueba t, estas condiciones son:

1. Las observaciones son elegidas independientes entre si.
2. Las observaciones provienen de una poblacion con distribucion cercana a la normal.

y esta prueba se puede extender a diferencia de las medias de dos poblaciones a partir de dos muestras independientes.

1.- Cada muestra cumple las condiciones para usar la distribucion t.
2.- Las dos muestras son independientes entre si.

Es por eso si el escenario no cumple con alguna de estas condiciones podemos utilizar la prueba de suma de rangos de Wilcoxon.

**Condiciones para usar la prueba de suma de rangos de Wilcoxon**

1. Las observaciones de ambas muestras son independientes.
2. La escala de medicion empleada debe ser a lo menos ordinal, de modo que tenga sentido hablar de relaciones de orden (igual que, mayor que, menor que)

Ejemplo:

una empresa de desarrollo de software desea evaluar la usabilidad de dos interfaces, A y B. con este fin la empresa selecciona al azar a 23 voluntarios y voluntarias quienes son asignados de manera aleatoria a dos grupos, cada uno de los cuales debe probar una interfaz.
N_a = 12, N_b = 11. donde cada participante evalua 6 aspectos con nota de 1 a 7, los datos muestran el promedio otorgado por cada participante.

**Datos del problema**

```{r}
# Ingresar los datos
Interfaz_A <- c(2.7, 6.6, 1.6, 5.1, 3.7, 6.1, 5.0, 1.4, 1.8, 1.5, 3.0, 5.3)
Interfaz_B <- c(5.0, 1.4, 5.6, 4.6, 6.7, 2.7, 1.3, 6.3, 3.7, 1.3, 6.8)

```

Como nos pide comparar dos muestras independientes, primero verificaremos las condiciones para utilizar una prueba t de student.

